require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvertismentsController do

  # This should return the minimal set of attributes required to create a valid
  # Advertisment. As you add validations to Advertisment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "img_url" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvertismentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all advertisments as @advertisments" do
      advertisment = Advertisment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:advertisments).should eq([advertisment])
    end
  end

  describe "GET show" do
    it "assigns the requested advertisment as @advertisment" do
      advertisment = Advertisment.create! valid_attributes
      get :show, {:id => advertisment.to_param}, valid_session
      assigns(:advertisment).should eq(advertisment)
    end
  end

  describe "GET new" do
    it "assigns a new advertisment as @advertisment" do
      get :new, {}, valid_session
      assigns(:advertisment).should be_a_new(Advertisment)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertisment as @advertisment" do
      advertisment = Advertisment.create! valid_attributes
      get :edit, {:id => advertisment.to_param}, valid_session
      assigns(:advertisment).should eq(advertisment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Advertisment" do
        expect {
          post :create, {:advertisment => valid_attributes}, valid_session
        }.to change(Advertisment, :count).by(1)
      end

      it "assigns a newly created advertisment as @advertisment" do
        post :create, {:advertisment => valid_attributes}, valid_session
        assigns(:advertisment).should be_a(Advertisment)
        assigns(:advertisment).should be_persisted
      end

      it "redirects to the created advertisment" do
        post :create, {:advertisment => valid_attributes}, valid_session
        response.should redirect_to(Advertisment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertisment as @advertisment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisment.any_instance.stub(:save).and_return(false)
        post :create, {:advertisment => { "img_url" => "invalid value" }}, valid_session
        assigns(:advertisment).should be_a_new(Advertisment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisment.any_instance.stub(:save).and_return(false)
        post :create, {:advertisment => { "img_url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertisment" do
        advertisment = Advertisment.create! valid_attributes
        # Assuming there are no other advertisments in the database, this
        # specifies that the Advertisment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Advertisment.any_instance.should_receive(:update_attributes).with({ "img_url" => "MyString" })
        put :update, {:id => advertisment.to_param, :advertisment => { "img_url" => "MyString" }}, valid_session
      end

      it "assigns the requested advertisment as @advertisment" do
        advertisment = Advertisment.create! valid_attributes
        put :update, {:id => advertisment.to_param, :advertisment => valid_attributes}, valid_session
        assigns(:advertisment).should eq(advertisment)
      end

      it "redirects to the advertisment" do
        advertisment = Advertisment.create! valid_attributes
        put :update, {:id => advertisment.to_param, :advertisment => valid_attributes}, valid_session
        response.should redirect_to(advertisment)
      end
    end

    describe "with invalid params" do
      it "assigns the advertisment as @advertisment" do
        advertisment = Advertisment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisment.any_instance.stub(:save).and_return(false)
        put :update, {:id => advertisment.to_param, :advertisment => { "img_url" => "invalid value" }}, valid_session
        assigns(:advertisment).should eq(advertisment)
      end

      it "re-renders the 'edit' template" do
        advertisment = Advertisment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisment.any_instance.stub(:save).and_return(false)
        put :update, {:id => advertisment.to_param, :advertisment => { "img_url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertisment" do
      advertisment = Advertisment.create! valid_attributes
      expect {
        delete :destroy, {:id => advertisment.to_param}, valid_session
      }.to change(Advertisment, :count).by(-1)
    end

    it "redirects to the advertisments list" do
      advertisment = Advertisment.create! valid_attributes
      delete :destroy, {:id => advertisment.to_param}, valid_session
      response.should redirect_to(advertisments_url)
    end
  end

end
